version: "3.9"
services:
       node_js:
           container_name: node_js
           image: latest123/node_js
           build: .
           restart: always
           build: .
           ports:
             - 5000:3000
           environment:
             PORT: 3000
             MONGODB_URI: mongodb:mongodb:27017
             DB_NAME: my_db
             NAME: TrullyMittal
           depends_on:
             - mongodb
           links:
             - mongodb
       mongodb:
             image : mongo:latest
             container_name: mongodb
             volumes:
               - mongodb:/data/db
             ports:
               - 2717:27017
             restart: always

volumes:
  mongodb: {}



